CREATE TABLE IF NOT EXISTS news.media (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(100) NOT NULL,
  description varchar(5000),
  url varchar(500) NOT NULL UNIQUE,
  copyright varchar(5000),
  contact varchar(5000),
  "chiefEditor" varchar(300),
  address varchar(500),
  phone varchar(50),
  email varchar(200),
  "isActive" boolean NOT NULL DEFAULT true,
  logo varchar
);

CREATE TABLE IF NOT EXISTS news.news (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mediaId" integer NOT NULL,
  "externalId" varchar NOT NULL,
  "externalCode" varchar NOT NULL,
  date timestamp NOT NULL,
  header varchar(100) NOT NULL,
  summary text,
  text text,
  url varchar(500) UNIQUE,
  CONSTRAINT news_media_external_code_unique UNIQUE ("mediaId", "externalCode")
);

CREATE TABLE IF NOT EXISTS news.image (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "newsId" integer NOT NULL,
  "newsUrl" varchar NOT NULL,
  src text,
  alt text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS news.link (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "newsId" integer NOT NULL,
  "newsUrl" varchar NOT NULL,
  href text,
  rel text DEFAULT '',
  "textContent" text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS news.log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar NOT NULL,
  value varchar NOT NULL,
  timestamp timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS news."user" (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(200) NOT NULL UNIQUE,
  email varchar(200) NOT NULL UNIQUE
);
