CREATE TABLE IF NOT EXISTS news.media_parser_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mediaId" integer NOT NULL UNIQUE REFERENCES news.media(id) ON DELETE CASCADE,
  "articleLinkSelector" varchar(1000) NOT NULL,
  "headerSelector" varchar(1000) NOT NULL,
  "dateSelector" varchar(1000) NOT NULL,
  "summarySelector" varchar(1000),
  "textSelector" varchar(1000) NOT NULL,
  "linkSelector" varchar(1000),
  "imageSelector" varchar(1000),
  "externalCodeStrategy" varchar(50) NOT NULL,
  "externalIdStrategy" varchar(50) NOT NULL,
  "publicationDateStrategy" varchar(50) NOT NULL,
  "sameHostOnly" boolean NOT NULL DEFAULT true,
  "excludedUrlPatterns" jsonb NOT NULL DEFAULT '[]'::jsonb
);

INSERT INTO news.media_parser_config (
  "mediaId", "articleLinkSelector", "headerSelector", "dateSelector",
  "summarySelector", "textSelector", "linkSelector", "imageSelector",
  "externalCodeStrategy", "externalIdStrategy", "publicationDateStrategy",
  "sameHostOnly", "excludedUrlPatterns"
)
SELECT
  id, '.listing__column_main-news a', '.article>.article__heading', '.article time',
  '.article>.article__summary', '.article>.article__text>p', '.article__text a',
  '.article img', 'last-path-segment', 'code-prefix', 'datetime-attribute',
  true, '["cnComments"]'::jsonb
FROM news.media WHERE url = 'https://russian.rt.com'
ON CONFLICT ("mediaId") DO NOTHING;

INSERT INTO news.media_parser_config (
  "mediaId", "articleLinkSelector", "headerSelector", "dateSelector",
  "summarySelector", "textSelector", "linkSelector", "imageSelector",
  "externalCodeStrategy", "externalIdStrategy", "publicationDateStrategy",
  "sameHostOnly", "excludedUrlPatterns"
)
SELECT
  id, '.cell-list__item-link', '.article__header>.article__title',
  '.article__info-date a', '.article__header>.article__second-title',
  '.article__body>.article__block>.article__text', null, null,
  'ria-article', 'ria-article', 'ria-text', true, '[]'::jsonb
FROM news.media WHERE url = 'https://ria.ru'
ON CONFLICT ("mediaId") DO NOTHING;

INSERT INTO news.media_parser_config (
  "mediaId", "articleLinkSelector", "headerSelector", "dateSelector",
  "summarySelector", "textSelector", "linkSelector", "imageSelector",
  "externalCodeStrategy", "externalIdStrategy", "publicationDateStrategy",
  "sameHostOnly", "excludedUrlPatterns"
)
SELECT
  id, '.newstoplist ul li a', '.news_container h1',
  '.news_container .article-date-desktop', '.news_container .Anonce>p',
  '.news_container>p', '.news_container a', '.news_container img',
  'last-path-segment', 'code', 'russian-month-text', true, '[]'::jsonb
FROM news.media WHERE url = 'https://www.cnews.ru'
ON CONFLICT ("mediaId") DO NOTHING;
